config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', passwords: 'users/passwords', registrations: 'users/registrations'
  }

  resource :two_factor_settings, except: %i[index show]

  root to: 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :otp_plain_backup_codes

  devise :two_factor_authenticatable, :two_factor_backupable,
         otp_backup_code_length: 10, otp_number_of_backup_codes: 10,
         otp_secret_encryption_key: ENV.fetch('OTP_SECRET_KEY', nil)
  devise :registerable, :recoverable, :lockable,
         :secure_validatable, :timeoutable, :password_archivable

  serialize :otp_backup_codes, JSON

  def generate_two_factor_secret_if_missing!
    return unless otp_secret.nil?

    update!(otp_secret: User.generate_otp_secret)
  end

  def enable_two_factor!
    update!(otp_required_for_login: true)
  end

  def disable_two_factor!
    update!(otp_required_for_login: false, otp_secret: nil, otp_backup_codes: nil)
  end

  def two_factor_qr_code_uri
    issuer = ENV.fetch('OTP_2FA_ISSUER_NAME', nil)
    label = [issuer, email].join(':')

    otp_provisioning_uri(label, issuer:)
  end

  def two_factor_backup_codes_generated?
    otp_backup_codes.present?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:otp_attempt])
  end
end

app/controllers/concerns/authenticate_with_otp_two_factor.rb
# frozen_string_literal: true

module AuthenticateWithOtpTwoFactor
  extend ActiveSupport::Concern

  def authenticate_with_otp_two_factor
    user = self.resource = find_user

    if user_params[:otp_attempt].present? && session[:otp_user_id]
      authenticate_user_with_otp_two_factor(user)
    elsif user&.valid_password?(user_params[:password])
      prompt_for_otp_two_factor(user)
    end
  end

  private

  def valid_otp_attempt?(user)
    user.validate_and_consume_otp!(user_params[:otp_attempt]) ||
      user.invalidate_otp_backup_code!(user_params[:otp_attempt])
  end

  def prompt_for_otp_two_factor(user)
    @user = user

    session[:otp_user_id] = user.id
    render 'users/sessions/two_factor'
  end

  def authenticate_user_with_otp_two_factor(user)
    if valid_otp_attempt?(user)
      session.delete(:otp_user_id)

      remember_me(user) if user_params[:remember_me] == '1'
      user.save!
      sign_in_user
    else
      flash.now[:alert] = 'Invalid two-factor code.'
      prompt_for_otp_two_factor(user)
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :remember_me, :otp_attempt)
  end

  def find_user
    if session[:otp_user_id]
      User.find(session[:otp_user_id])
    elsif user_params[:email]
      User.find_by(email: user_params[:email])
    end
  end

  def otp_two_factor_enabled?
    find_user&.otp_required_for_login
  end

  def sign_in_user
    sign_in(resource_name, resource, event: :authentication)
    respond_with resource, location: after_sign_in_path_for(resource)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/two_factor_settings_controller.rb
# frozen_string_literal: true

class TwoFactorSettingsController < ApplicationController
  def new
    if current_user.otp_required_for_login
      flash[:alert] = 'Two Factor Authentication is already enabled.'
      return redirect_to edit_user_registration_path
    end

    current_user.generate_two_factor_secret_if_missing!
  end

  def create
    unless current_user.valid_password?(enable_2fa_params[:password])
      flash.now[:alert] = 'Incorrect password'
      return render :new
    end

    if current_user.validate_and_consume_otp!(enable_2fa_params[:code])
      enable_user_two_factor!
    else
      flash.now[:alert] = 'Incorrect Code'
      render :new
    end
  end

  def edit
    unless current_user.otp_required_for_login
      flash[:alert] = 'Please enable two factor authentication first.'
      return redirect_to new_two_factor_settings_path
    end

    if current_user.two_factor_backup_codes_generated?
      flash[:alert] = 'You have already seen your backup codes.'
      return redirect_to edit_user_registration_path
    end

    @backup_codes = current_user.generate_otp_backup_codes!
    current_user.save!
  end

  def destroy
    if current_user.disable_two_factor!
      flash[:notice] = 'Successfully disabled two factor authentication.'
      redirect_to edit_user_registration_path
    else
      flash[:alert] = 'Could not disable two factor authentication.'
      redirect_back fallback_location: root_path
    end
  end

  private

  def enable_2fa_params
    params.require(:two_fa).permit(:code, :password)
  end

  def enable_user_two_factor!
    current_user.enable_two_factor!

    flash[:notice] = 'Successfully enabled two factor authentication, please make note of your backup codes.'
    redirect_to edit_two_factor_settings_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    prepend_before_action :check_captcha, only: [:create]

    private

    def check_captcha
      return if verify_recaptcha

      self.resource = resource_class.new

      respond_with_navigational(resource) do
        flash.discard(:recaptcha_error)
        render :new
      end
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    prepend_before_action :check_captcha, only: [:create]

    private

    # :nocov:
    def check_captcha
      return if verify_recaptcha

      self.resource = resource_class.new sign_up_params
      resource.validate
      set_minimum_password_length

      respond_with_navigational(resource) do
        flash.discard(:recaptcha_error)
        render :new
      end
    end
    # :nocov:
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    include AuthenticateWithOtpTwoFactor

    prepend_before_action :check_captcha, only: [:create]
    prepend_before_action :authenticate_with_otp_two_factor,
                          if: -> { action_name == 'create' && otp_two_factor_enabled? }

    protect_from_forgery with: :exception, prepend: true, except: :destroy

    private

    # :nocov:
    def check_captcha
      return if verify_recaptcha

      self.resource = resource_class.new sign_in_params

      respond_with_navigational(resource) do
        flash.discard(:recaptcha_error)
        render :new
      end
    end
    # :nocov:
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  INFO = 'alert alert-info'
  SUCCESS = 'alert alert-success'
  DANGER = 'alert alert-danger'

  def flash_class(level)
    case level.to_sym
    when :notice then INFO
    when :success then SUCCESS
    when :error, :alert, :recaptcha_error then DANGER
    end
  end
end

app/helpers/qr_code_helper.rb
# frozen_string_literal: true

module QrCodeHelper
  def qr_code_as_svg(uri)
    RQRCode::QRCode.new(uri).as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 4,
      standalone: true
    ).html_safe
  end
end

app/views/home/index.html.erb
<p>You are currently logged in as <%= current_user.email %>.</p>
<p>Use menu to navigate</p>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="<%= flash_class(type) %>">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginEspresso</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <% if current_user %>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <%= link_to 'Home', root_path, class: 'navbar-brand'  %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <%= link_to 'Settings', edit_user_registration_path, class: 'nav-link'  %>
              </li>
              <li class="nav-item">
                <%= button_to 'Logout', destroy_user_session_path, class: 'nav-link', method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }  %>
              </li>
            </ul>
          </div>
        </nav>
      <% end %>

      <%= yield %>

    </div>
  </body>
</html>

app/views/two_factor_settings/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>Two Factor Authentication</h2>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <div class="card">
        <div class="card-header">
          Backup Codes
        </div>
        <div class="card-body">
          <p>Keep these backup codes safe in case you lose access to your authenticator app:</p>
          <hr />
          <% @backup_codes.each_slice(2) do |(code1, code2)| %>
            <div class="row">
              <div class="col-6 text-monospace strong"><%=code1 %></div>
              <div class="col-6 text-monospace strong"><%=code2 %></div>
            </div>
          <% end %>
        </div>
      </div>
      <br />
      <div class="card">
        <div class="card-header">
          Two Factor Setup Complete
        </div>
        <div class="card-body">
          <p>Two factor authentication has been successfully enabled.</p>
          <%= link_to('Return to account settings', edit_user_registration_path, class: 'btn btn-primary') %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/two_factor_settings/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>Two Factor Authentication</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="card-deck">
      <div class="card">
        <div class="card-header">
          1. Scan QR Code
        </div>
        <div class="card-body">
          <p>Please scan the below QR code using an OTP compatible app (such as Google Authenticator or Authy).</p>
          <hr />
          <p class="text-center">
            <%= qr_code_as_svg(current_user.two_factor_qr_code_uri)%>
          </p>
          <hr />
          <p class="text-center">
            If you cannot scan, please enter the following code manually: <code><%= current_user.otp_secret%></code>
          </p>
        </div>
      </div>
      <br />
      <div class="card">
        <div class="card-header">
          2. Confirm OTP Code
        </div>
        <div class="card-body">
          <p>Please confirm that your authentication application is working by entering a generated code below.</p>
          <%= form_for(:two_fa, url: two_factor_settings_path, method: :post) do |f| %>
            <%= render 'layouts/flash' %>
            <div class="form-group">
              <%= f.label :code %>
              <%= f.text_field :code, class: 'form-control' %>
            </div>
            <br />

            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control' %>
            </div>
            <br />

            <div class="form-group">
              <%= f.submit 'Confirm and Enable Two Factor', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>